apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-1lpe
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-1lpe
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-1lpe
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-1lpe
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-1lpe
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-rgqs-tenant/rhtap-demo-app/hacbs-test-project-1lpe@sha256:c95725f189696277752b32867834647c321b6b357c0785079e68e10e5ee0de93
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
